
@NonCPS def sKaymeraRepositoryPath = "/mnt/data/projects/Kaymera_Apps"
@NonCPS def sBuildScriptPath = sKaymeraRepositoryPath + "/Android/Kmtd/jenkins" 
@NonCPS def sGerritUrl = "http://gerrit02.kaymera.com:8080/KaymeraRepository.git"
@NonCPS def sCredentialsId = "50192fae-78ac-46bc-b1ed-ae63a802c0a1"
@NonCPS def sBranch = "master"
@NonCPS def sBuildCommandToRun = "./build.sh"
@NonCPS def sCopyToSMB = "/mnt/data/SharedScripts/copyAMTDapp.sh"
@NonCPS def sOutputFiles = [sKaymeraRepositoryPath + "/Android/Kmtd/app/build/outputs/apk/app-debug.apk",
					sKaymeraRepositoryPath + "/Android/Kmtd/app/build/outputs/apk/app-release-unsigned.apk",
					sKaymeraRepositoryPath + "/Android/Kmtd/app/build/outputs/mapping/release/mapping.txt"]

@NonCPS def sApkSignerToolPath = "/mnt/data/Tools/android-sdk-linux/build-tools/25.0.1/apksigner "
@NonCPS def sKmtdCertJKSPath = "/tmp/tmp.8SAZjSnLKr/debugcert.jks "
@NonCPS def sKmtdCertJKSPassword = "android "
@NonCPS def sKmtdSignedDestPath = "/tmp/tmp.8SAZjSnLKr/rel-signed.apk "
@NonCPS def sKmtdRelUnsignedSrcPath = sKaymeraRepositoryPath + "/Android/Kmtd/app/build/outputs/apk/app-release-unsigned.apk "
@NonCPS def verficationsCommands = " -v --print-certs "
@NonCPS def command = sApkSignerToolPath 
						+ " sign --ks " 
						+ sKmtdCertJKSPath 
						+ " --out " 
						+ sKmtdSignedDestPath 
						+ sKmtdRelUnsignedSrcPath 
						+ verficationsCommands
node {
	stage ('Prepare'){
		dir (sKaymeraRepositoryPath) {
			git credentialsId: sCredentialsId, 
				url: sGerritUrl,
				branch: sBranch
		}
	}

	stage ('Build'){
		dir(sBuildScriptPath){
			sh sBuildCommandToRun
		}
	}

	stage ('Verify'){
		for (file in sOutputFiles ) {
			if (fileExists(file)) { 
				echo file + ' exist' 
			} else { 
				echo file + ' Not exist' 
			}	
		}
	}

	stage ('Copy to SMB'){
		sh sCopyToSMB
	    }

	stage ('Sign') {
		sh command
	}

}
